INSERT INTO `quest_greeting` VALUES (234, 0, 1, 0, 'A foul corruption has crept into Westfall.  While I was upholding my duty on the battlefields of Lordaeron these honest farms were overrun and made into hide-outs for thugs and murderers. The People\'s Militia needs your help.', 0);
INSERT INTO `quest_greeting` VALUES (235, 0, 0, 0, 'Welcome to our humble abode! It\'s always nice to see a friendly face. And what strong arms you have. My husband and I are always looking for help around the farm. Now that most the good folk have left, it\'s hard to find an able body to help out.', 0);
INSERT INTO `quest_greeting` VALUES (237, 0, 0, 0, 'Nothing but trouble in these parts.  I tried to tell that fool Saldean to get out while he still could but he won\'t hear of it.  But I ain\'t no fool.  Verna and I are gonna mosey on out as soon as we get this wagon fixed.', 0);
INSERT INTO `quest_greeting` VALUES (238, 0, 0, 0, 'Sometimes I think there\'s a big gray cloud in the sky, just raining down bad luck upon us. First, we\'re driven off our land, and now we can\'t even get out of Westfall. Everything\'s a mess. Something needs to be done.', 0);
INSERT INTO `quest_greeting` VALUES (241, 0, 0, 0, 'Hey there, friend.  My name\'s Remy.$BI\'m from Redridge to the east, and came here looking for business, looking for business.  You got any...got any??', 0);
INSERT INTO `quest_greeting` VALUES (253, 0, 0, 0, 'Aha! Good day, good day, Master $C! Come, sit down and have a drink. You have an enterprising look in your eye, and I think you\'ll find speaking to me worth your time...', 0);
INSERT INTO `quest_greeting` VALUES (261, 0, 0, 0, 'Hello, citizen.  You look like a $g man : woman; with a purpose - do you have business with the Stormwind Army?', 0);
INSERT INTO `quest_greeting` VALUES (342, 0, 0, 0, 'Hail, $n. Welcome to my humble garden. The weather has been perfect lately. Let us hope it holds steady for a ripe harvest.', 0);
INSERT INTO `quest_greeting` VALUES (714, 0, 0, 0, 'Greetings, $c! Fine day for hunting, wouldn\'t you say? I\'ve been having more than a little luck with boars, myself. Perhaps you\'d like a shot?', 0);
INSERT INTO `quest_greeting` VALUES (786, 0, 0, 0, 'Greetings, $G lad : lass;. I\'m Grelin Whitebeard. I\'m here to examine the threat posed by the growing numbers of trolls in Coldridge Valley. What have I found? It\'s a bit troubling...', 0);
INSERT INTO `quest_greeting` VALUES (823, 0, 1, 0, 'Hello there, $c.  Normally I\'d be out on the beat looking after the folk of Stormwind, but a lot of the Stormwind guards are fighting in the other lands.  So here I am, deputized and offering bounties when I\'d rather be on patrol...', 0);
INSERT INTO `quest_greeting` VALUES (1343, 0, 0, 0, 'Well, if it isn\'t a young, bristling $c, no doubt drawn here by talk of my exploits in fields of battle!$B$BNo time for stories now, for there are great, important deeds that need doing!  So if you\'re looking for glory, then luck shines on you today...', 0);
INSERT INTO `quest_greeting` VALUES (1374, 0, 0, 0, 'Curse that Brewers\' League! They have access to all the best ingredients, while we\'re stuck here grubbing for grain and hops!$B$BI really would like to give them some bitter tasting justice...', 0);
INSERT INTO `quest_greeting` VALUES (1495, 0, 0, 0, 'Greetings, $C. Be wary as you travel east toward The Bulwark. Recent surveillance reports indicate increased Scourge activity in that area, so exercise caution.', 0);
INSERT INTO `quest_greeting` VALUES (1499, 0, 0, 0, 'Ah, you there! I have tasks to give, and I need not waste time explaining their crucial nature. Listen close.', 0);
INSERT INTO `quest_greeting` VALUES (1500, 0, 0, 0, 'I hope you\'re well, all things considered.$B$BSit for a spell, and hear my tale. It\'s a tragedy, of course, but one I hope will end in revenge!', 0);
INSERT INTO `quest_greeting` VALUES (1515, 0, 0, 0, 'The Scarlet Crusade is encroaching on our homeland. The foolish zealots do not realize that the loyal servants of The Dark Lady shall see to their demise.', 0);
INSERT INTO `quest_greeting` VALUES (1518, 0, 0, 0, 'The Dark Lady has put forth the challenge. It is up to us to meet it.', 0);
INSERT INTO `quest_greeting` VALUES (2519, 0, 0, 0, 'Hello!  The spirits say you here to aid my chief.  Say it loud, they do.', 0);
INSERT INTO `quest_greeting` VALUES (2546, 0, 0, 0, 'Yarrr... ye best not be trifling with my time, matey!', 0);
INSERT INTO `quest_greeting` VALUES (2930, 0, 0, 0, 'Corruption sneaks into nature\'s grove. The forest must be protected at all costs.', 0);
INSERT INTO `quest_greeting` VALUES (3139, 0, 0, 0, 'Throm\'ka, $c. There is little time for talk and much work to be done.', 0);
INSERT INTO `quest_greeting` VALUES (3188, 0, 0, 0, 'There is something you wish to discuss, $c... come, sit by me.', 0);
INSERT INTO `quest_greeting` VALUES (3338, 0, 0, 0, 'The land, the water and the sky are all as one. It is your eyes that deceive you with such separation. The Earthmother is all those things and more.', 0);
INSERT INTO `quest_greeting` VALUES (3391, 0, 0, 0, 'Thrall paid me and my boys well for helping out with the construction of Orgrimmar, so I decided to set up a port here. We do most of our business through Booty Bay and Baron Revilgaz.', 15595);
INSERT INTO `quest_greeting` VALUES (3419, 0, 1, 0, 'For our people to survive, we must study the ways of nature and learn its secrets.', 0);
INSERT INTO `quest_greeting` VALUES (3446, 0, 0, 0, 'Yes yes yes! You\'re just the $r I\'m looking for!$B$BSit! We have much to discuss!!', 0);
INSERT INTO `quest_greeting` VALUES (3453, 0, 0, 0, 'Something I can help you with, $n? There\'s a shipment I\'ve got to see to otherwise.', 0);
INSERT INTO `quest_greeting` VALUES (3390, 0, 0, 0, 'The Barrens holds a variety of substances for which we, the apothecaries of Lordaeron may find use.', 0);
INSERT INTO `quest_greeting` VALUES (3616, 0, 0, 0, 'The wind whispers to those who listen...$B$BDo you hear it?', 0);
INSERT INTO `quest_greeting` VALUES (3649, 0, 1, 0, 'Dark forces encroach upon our borders, ancient taints resurface, and new evils emerge to topple the delicate balance of the land. In times of such darkness, we all must be vigilant.', 0);
INSERT INTO `quest_greeting` VALUES (4077, 0, 0, 0, 'If I can get the proper ingredients, we can create some explosives that will not only allow me to damage the Venture\'s Co.\'s operations, but also cause a distraction.$B$BI know you\'re impressed, but it gets better... I\'ll tell you more soon enough.', 0);
INSERT INTO `quest_greeting` VALUES (4453, 0, 0, 0, 'Be careful where you put that foot of yours, $g sir : ma\'am;. We\'re not all blessed with the lofty height of a gnome.', 0);
INSERT INTO `quest_greeting` VALUES (5887, 0, 0, 0, 'I welcome you back, $n.', 0);
INSERT INTO `quest_greeting` VALUES (6171, 0, 1, 0, 'You will be tested many times by the darkness that surrounds our lands, $N. But to ensure you are always prepared, we will often ask tasks of you so you are at the height of your own power.$B$BGo with the Light, and remain virtuous.', 0);
INSERT INTO `quest_greeting` VALUES (7407, 0, 0, 0, 'The name\'s Bilgewhizzle, and I am the chief engineer of the Gadgetzan Water Company.  What can I assist you with?', 0);
INSERT INTO `quest_greeting` VALUES (7876, 0, 0, 0, 'Some people wonder what we\'re doing out here in the desert.  Well... If I told you, then you\'d stay and try to make our profits!', 0);
INSERT INTO `quest_greeting` VALUES (27337, 0, 0, 0, '', 0);
INSERT INTO `quest_greeting` VALUES (240, 0, 0, 0, 'Ach, it\'s hard enough keeping order around here without all these new troubles popping up!  I hope you have good news, $n...', 0);
INSERT INTO `quest_greeting` VALUES (344, 0, 5, 0, 'Redridge is awash in chaos!', 0);
INSERT INTO `quest_greeting` VALUES (3339, 0, 0, 0, 'This had better be good...', 0);
INSERT INTO `quest_greeting` VALUES (3995, 0, 5, 0, 'The spirits are restless!', 0);
INSERT INTO `quest_greeting` VALUES (4049, 0, 0, 0, 'The spirit of Stonetalon weeps... It weeps from its mountain peaks, to its rivers, to its severed, dying trees.', 0);
INSERT INTO `quest_greeting` VALUES (264, 0, 0, 0, 'At ease, $c. If you are just passing though I suggest you stick to the roads and only travel by day. If your business is here in Darkshire, consider lending your abilities to the Night Watch. Our Skill is unquestionable but our numbers are small.', 0);
INSERT INTO `quest_greeting` VALUES (3519, 0, 0, 0, 'I, Arynia Cloudsbreak, have been tasked with protecting the sanctity of the Oracle Grove.', 0);
INSERT INTO `quest_greeting` VALUES (392, 0, 0, 0, 'Do not be alarmed, $r.  I have long since passed from this land but I intend no harm to your kind.  I have witnessed too much death in my time.  My only wish now is for peace.  Perhaps you can help my cause.', 0);
INSERT INTO `quest_greeting` VALUES (900, 0, 6, 0, 'What business brings you before the Court of Lakeshire and the Honorable Magistrate Solomon?', 0);
INSERT INTO `quest_greeting` VALUES (2080, 0, 1, 0, 'The creation of Teldrassil was a grand achievement, but now the world must shift to regain its balance.', 0);
INSERT INTO `quest_greeting` VALUES (3337, 0, 0, 0, 'The heft of an axe, the battlecry of your allies, the spray of blood in your face. These are the things a warrior craves, $n. I will carve out The Barrens with my sword in the name of the Horde.', 0);
INSERT INTO `quest_greeting` VALUES (3567, 0, 1, 0, 'Well met, $n. It is good to see that $cs like yourself are taking an active part in protecting the groves.', 0);
INSERT INTO `quest_greeting` VALUES (4791, 0, 1, 0, 'We may not be in open war with the Alliance, but blood is still shed between us.', 0);
INSERT INTO `quest_greeting` VALUES (5767, 0, 1, 0, 'Our only hope is to create something good from an already bad situation.', 0);
INSERT INTO `quest_greeting` VALUES (3847, 0, 0, 0, 'Ashenvale is a lush forest, brimming with life. It is a pleasure to walk down its secret paths in search of herbs, but one must take care. The forest is not without its dangers.', 0);
INSERT INTO `quest_greeting` VALUES (11862, 0, 0, 0, '', 0);
INSERT INTO `quest_greeting` VALUES (10537, 0, 0, 0, 'We cannot take care of all the threats in this area alone. We could use another fighting hand, $n.', 0);
INSERT INTO `quest_greeting` VALUES (2216, 0, 0, 0, 'We are but so close to developing the New Plague that our Dark Lady desires with such fervor.', 0);
INSERT INTO `quest_greeting` VALUES (4452, 0, 0, 0, 'Come a little closer.  We have important matters to discuss, you and I.$B$BAnd some of them we don\'t want everyone to hear...', 0);
INSERT INTO `quest_greeting` VALUES (4046, 0, 1, 0, 'You must listen, young $c.  Listen to the whisperings in the darkness, for they offer guidance in these troubled times.', 0);
INSERT INTO `quest_greeting` VALUES (2706, 0, 0, 0, 'Thanks to the Warchief, even here in the ruins of our former prison some hope remains, and the Horde rises anew.', 0);
INSERT INTO `quest_greeting` VALUES (5412, 0, 0, 0, 'The centaur clans rule the wastes of Desolace. If united, they would be a terrible force. It is then good that the centaur clans are not united but instead bicker and war amongst themselves.', 0);
INSERT INTO `quest_greeting` VALUES (5641, 0, 1, 0, 'The main threat Thrall wishes dealt with is the Burning Blade---members of the Horde that have given their loyalty to the demons. They seek to practice their dark magic and care little for Thrall\'s visions of the Horde\'s future here in Kalimdor.', 0);
INSERT INTO `quest_greeting` VALUES (4498, 0, 0, 0, 'Greetings, $c.', 0);
INSERT INTO `quest_greeting` VALUES (2817, 0, 0, 0, 'You must be hard up to be wandering this Badlands, $c. A hard up like me.$B$BOr maybe you\'re here because you\'re crazy. Crazy, like me.', 0);
INSERT INTO `quest_greeting` VALUES (737, 0, 0, 0, 'Well, hello there. You seem like you wouldn\'t be opposed to making some coin, hm? I can tell from the look in your eyes. I am Mogul Kebok, overseer of operations in Azeroth, and if it is riches you seek, perhaps I can make arrangements.', 0);
INSERT INTO `quest_greeting` VALUES (773, 0, 0, 0, '$C, eh? I am Krazek, Baron Revilgaz\'s secretary. I know everything about the goings on in this jungle and beyond. Perhaps you\'d be interested in knowing the going price on oil in Ratchet? No? Looking for work, maybe? I can help you there.', 0);
INSERT INTO `quest_greeting` VALUES (1937, 0, 0, 0, 'The Dark Lady has put the challenge forth.  Now it is up to the Royal Apothecary Society to develop a new plague.  We shall bring Arthas and his wretched army to their knees.', 0);
INSERT INTO `quest_greeting` VALUES (2076, 1, 0, 0, 'This cauldron churns with thick, green bubbles.  Skulls, bones and organs of unknown creatures swim within its viscous broth...$B$BAnd rising lazily to the surface are the skulls of two, once mighty trolls:$B$BGan\'zulah and Nezzliok.', 0);
INSERT INTO `quest_greeting` VALUES (2121, 0, 0, 0, 'Information... With our scouts and agents, we control the flow of information in Lordaeron. Scourge movements, their holdings, all underneath our watchful eyes...', 0);
INSERT INTO `quest_greeting` VALUES (2285, 0, 0, 0, 'My family boasts the finest collection of jewelry and objects of fine art among all the nobles of Stormwind!$B$BAnd we are always wishing to increase the size our collection...', 0);
INSERT INTO `quest_greeting` VALUES (2498, 0, 0, 0, 'What what?!?  We all have profit to make... and we won\'t do it by standing idle.', 0);
INSERT INTO `quest_greeting` VALUES (2921, 0, 0, 0, 'How perfect of you to come by, $c.$B$BMy name is Lotwil Veriatus, founding member of the Enlightened Assembly of Arcanology, Alchemy, and Engineering Sciences: we seek to blend the intelligent sciences of Azeroth together into one comprehensive school.', 0);
INSERT INTO `quest_greeting` VALUES (3845, 0, 0, 0, 'We elves have a long history.  Let us hope this history does not return to haunt us.', 0);
INSERT INTO `quest_greeting` VALUES (5204, 0, 0, 0, 'If we are to make our place in this world, then we will do so through study, and through the will to ignore our fading human instincts.', 0);
INSERT INTO `quest_greeting` VALUES (5394, 0, 1, 0, 'Don\'t let the heat bother you.  In the Badlands, heat is the least of your worries.', 0);
INSERT INTO `quest_greeting` VALUES (5591, 0, 1, 0, 'This sty\'s a little shy of comfy, but it has history, so Stonard must be important to someone. I\'d gamble that\'s why we stay here. It sure ain\'t for the view--it don\'t even look like home.', 0);
INSERT INTO `quest_greeting` VALUES (7882, 0, 1, 0, 'We\'re here to make a profit.  And having our goods stolen is no way to make a profit.', 0);
INSERT INTO `quest_greeting` VALUES (7900, 0, 0, 0, 'Hello, $N. Perhaps you have some time to chat?', 0);
INSERT INTO `quest_greeting` VALUES (9078, 0, 1, 0, 'Dear $g boy:girl;, you have arrived just in time to assist the Kargath Expeditionary Force.', 0);
INSERT INTO `quest_greeting` VALUES (10926, 0, 0, 0, 'I never feel warm anymore...', 0);
INSERT INTO `quest_greeting` VALUES (11039, 0, 1, 0, 'Greetings, $N. I am Duke Nicholas Zverenhoff of the Argent Dawn.', 0);
INSERT INTO `quest_greeting` VALUES (22292, 0, 396, 0, 'The Light does not yet shine on Skettis.', 0);
INSERT INTO `quest_greeting` VALUES (1776, 0, 0, 0, 'We spent so much of our lives in fight, memories of peaceful times grow evermore distant.', 0);
INSERT INTO `quest_greeting` VALUES (3441, 0, 0, 0, 'To hunt a beast, one must know that beast.  One must learn and respect its ways.$B$BTo do otherwise is not to hunt.  To do otherwise is merely to kill.', 0);
INSERT INTO `quest_greeting` VALUES (4500, 0, 0, 0, 'Overlord Mok\'Morokk boss. You do what I say.', 0);
INSERT INTO `quest_greeting` VALUES (7777, 0, 0, 0, '', 0);
INSERT INTO `quest_greeting` VALUES (9536, 0, 0, 0, 'The quest for wealth is the only goal for a respectable goblin.$B$BWell, maybe wealth... and a big, loud death!', 0);
INSERT INTO `quest_greeting` VALUES (1950, 0, 0, 0, 'My brother and I are on a scouting mission, but we are holed up in this farmhouse. The Deathstalkers need your help!', 0);
INSERT INTO `quest_greeting` VALUES (7825, 0, 0, 0, '', 0);
INSERT INTO `quest_greeting` VALUES (6986, 0, 1, 0, 'My name is Dran Droffers, and this over here is my dummy son Malton.  If you need salvage, or are looking to sell salvage, then we\'re who you need to be talking to!', 0);
INSERT INTO `quest_greeting` VALUES (4485, 0, 1, 0, 'The days grow long, and still no end to the conflicts of these lands can be seen. It takes no spell caster to know that much. Take up a blade while you can, $c. War can come to our doors at any time, and if I\'m not mistaken, you look to be one who revels in it.', 0);
INSERT INTO `quest_greeting` VALUES (2501, 0, 0, 0, 'Oy!  You here for a game of knuckles?', 0);
INSERT INTO `quest_greeting` VALUES (733, 0, 0, 0, 'You watch where you step around here, $Glad:lass;.  You might not be a part of our outfit, but that doesn\'t mean I won\'t take a cane to you if you fall out of line!', 0);
INSERT INTO `quest_greeting` VALUES (5770, 0, 0, 0, 'If we are to protect nature, then we must embrace its strength.  And we must show this strength to those who would harm the land.', 0);
INSERT INTO `quest_greeting` VALUES (273, 0, 0, 0, 'Keep the door closed, $c. Never know when the Dark Riders will be passing through again.', 0);
INSERT INTO `quest_greeting` VALUES (1071, 0, 0, 0, 'If there\'s one thing that Rhag taught me it\'s that no assignment is a dull one. Protecting the Thandol Span should have been an easy task. But with the brunt of the army fighting alongside the Alliance, we were overwhelmed here and Dun Modr has fallen.', 0);
INSERT INTO `quest_greeting` VALUES (2713, 1, 0, 0, 'This wooden board holds roughly made wanted posters.', 0);
INSERT INTO `quest_greeting` VALUES (2700, 0, 0, 0, 'We at Refuge Pointe hold one of the few remaining patches of Stromgarde territory in the Arathi Highlands. And we\'re losing ground...$B$BIf you have words for me, then I hope they are good doings.', 0);
INSERT INTO `quest_greeting` VALUES (2276, 0, 0, 0, 'When I was first offered the title of Southshore Magistrate I was exalted to have earned such a commission so early in my career.$B$BBut now that I\'m here, I wonder if I\'d have been better off shuffling papers in Stormwind.', 0);
INSERT INTO `quest_greeting` VALUES (2263, 0, 0, 0, 'I hope you\'re here to work, $C. We have a lot to do and the Horde, the Syndicate and the Ogres aren\'t going to help us.', 0);
INSERT INTO `quest_greeting` VALUES (186420, 1, 0, 0, 'This collection of scrolls contains various logistic and strategic information, as well as coded correspondences.', 0);
INSERT INTO `quest_greeting` VALUES (265, 0, 0, 0, 'I have sensed your coming for quite some time, $n.  It was written in the pattern of the stars.', 0);
INSERT INTO `quest_greeting` VALUES (4794, 0, 0, 0, 'Researching in Theramore is an interesting job, but it\'s sure hard to find a soft bed in this town!', 0);
INSERT INTO `quest_greeting` VALUES (7884, 0, 0, 0, '', 0);
INSERT INTO `quest_greeting` VALUES (10306, 0, 0, 0, '', 0);
INSERT INTO `quest_greeting` VALUES (23572, 0, 0, 0, '', 0);
